/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ne10_sample_FFTComparator */

#ifndef _Included_com_example_ne10_sample_FFTComparator
#define _Included_com_example_ne10_sample_FFTComparator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ne10_sample_FFTComparator
 * Method:    doFFT
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ne10_1sample_FFTComparator_doFFT
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
