/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ne10_sample_Ne10Tester */

#ifndef _Included_com_example_ne10_sample_Ne10Tester
#define _Included_com_example_ne10_sample_Ne10Tester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ne10_sample_Ne10Tester
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ne10_1sample_Ne10Tester_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
